[2022-07-03 18:18:35,052] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Raize_ingestion.insert_data_on_pg__1 scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2022-07-03 18:18:35,068] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Raize_ingestion.insert_data_on_pg__1 scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2022-07-03 18:18:35,068] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-03 18:18:35,069] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-03 18:18:35,069] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-03 18:18:35,092] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): insert_data_on_pg__1> on 2022-07-02 00:00:00+00:00
[2022-07-03 18:18:35,102] {standard_task_runner.py:52} INFO - Started process 88 to run task
[2022-07-03 18:18:35,107] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Raize_ingestion', 'insert_data_on_pg__1', 'scheduled__2022-07-02T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag_raizen_ingestion.py', '--cfg-path', '/tmp/tmp_4vuuf3q', '--error-file', '/tmp/tmpiz1zq804']
[2022-07-03 18:18:35,108] {standard_task_runner.py:80} INFO - Job 26: Subtask insert_data_on_pg__1
[2022-07-03 18:18:35,206] {task_command.py:370} INFO - Running <TaskInstance: Raize_ingestion.insert_data_on_pg__1 scheduled__2022-07-02T00:00:00+00:00 [running]> on host 66e23168c4c8
[2022-07-03 18:18:35,347] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Raize_ingestion
AIRFLOW_CTX_TASK_ID=insert_data_on_pg__1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T00:00:00+00:00
[2022-07-03 18:18:35,349] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_raizen_ingestion.py", line 11, in inseret_data
    from dags.dag_raizen_ingestion import ExcelToPG
ModuleNotFoundError: No module named 'dags'
[2022-07-03 18:18:35,361] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Raize_ingestion, task_id=insert_data_on_pg__1, execution_date=20220702T000000, start_date=20220703T181835, end_date=20220703T181835
[2022-07-03 18:18:35,380] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task insert_data_on_pg__1 (No module named 'dags'; 88)
[2022-07-03 18:18:35,409] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-03 18:18:35,476] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
